language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "2.7"
  - "3.5"
env:
  - DJANGO_VERSION=1.7.10
  - DJANGO_VERSION=1.8.6
  - DJANGO_VERSION=1.9.10
  - DJANGO_VERSION=1.10.1
matrix:
  exclude:
    - python: "3.5"
      env: "DJANGO_VERSION=1.7.10"
install:
  - export XDG_CACHE_HOME=$HOME/.cache/
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
script:
 - pep8 yamlfield
 - pyflakes yamlfield
 - coverage run setup.py test
after_success:
  - coveralls
